import 'package:hive_flutter/hive_flutter.dart';

import '../../core/constants/app_constants.dart';

/// Hive boxes management.
/// 
/// Initializes and provides access to Hive boxes used for local storage.
class HiveBoxes {
  HiveBoxes._();

  static late Box<dynamic> _settingsBox;
  static late Box<dynamic> _playersBox;
  static late Box<dynamic> _categoriesBox;
  static late Box<dynamic> _tasksBox;
  static late Box<dynamic> _sessionsBox;

  /// Initializes all Hive boxes.
  static Future<void> initialize() async {
    // Register adapters
    _registerAdapters();
    
    // Open boxes
    _settingsBox = await Hive.openBox(AppConstants.settingsBoxKey);
    _playersBox = await Hive.openBox(AppConstants.playersBoxKey);
    _categoriesBox = await Hive.openBox(AppConstants.categoriesBoxKey);
    _tasksBox = await Hive.openBox(AppConstants.questionsBoxKey);
    _sessionsBox = await Hive.openBox(AppConstants.sessionsBoxKey);
  }

  static void _registerAdapters() {
    // Adapters will be generated by hive_generator
    // For now, we'll use JSON serialization
  }

  /// Settings box for app preferences.
  static Box<dynamic> get settings => _settingsBox;

  /// Players box for player data.
  static Box<dynamic> get players => _playersBox;

  /// Categories box for cached categories.
  static Box<dynamic> get categories => _categoriesBox;

  /// Tasks box for cached tasks.
  static Box<dynamic> get tasks => _tasksBox;

  /// Sessions box for game sessions.
  static Box<dynamic> get sessions => _sessionsBox;

  /// Clears all data from all boxes.
  static Future<void> clearAll() async {
    await _settingsBox.clear();
    await _playersBox.clear();
    await _categoriesBox.clear();
    await _tasksBox.clear();
    await _sessionsBox.clear();
  }
}
